/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.mkonrad.cvaccar;

public class cv_accar {
  public static void cv_accar_init(int camId, long camIntrinsicsAddr) {
    cv_accarJNI.cv_accar_init(camId, camIntrinsicsAddr);
  }

  public static void cv_accar_set_dbg_input_frame(long inFrameAddr) {
    cv_accarJNI.cv_accar_set_dbg_input_frame(inFrameAddr);
  }

  public static void cv_accar_set_dbg_output_mode(int mode) {
    cv_accarJNI.cv_accar_set_dbg_output_mode(mode);
  }

  public static void cv_accar_set_dbg_marker_shader(String vshSrc, String fshSrc) {
    cv_accarJNI.cv_accar_set_dbg_marker_shader(vshSrc, fshSrc);
  }

  public static void cv_accar_set_output_display_shader(String vshSrc, String fshSrc) {
    cv_accarJNI.cv_accar_set_output_display_shader(vshSrc, fshSrc);
  }

  public static void cv_accar_add_shader_to_pipeline(String vshSrc, String fshSrc) {
    cv_accarJNI.cv_accar_add_shader_to_pipeline(vshSrc, fshSrc);
  }

  public static void cv_accar_start() {
    cv_accarJNI.cv_accar_start();
  }

  public static void cv_accar_stop() {
    cv_accarJNI.cv_accar_stop();
  }

  public static void cv_accar_pause() {
    cv_accarJNI.cv_accar_pause();
  }

  public static void cv_accar_resume() {
    cv_accarJNI.cv_accar_resume();
  }

  public static void cv_accar_view_create() {
    cv_accarJNI.cv_accar_view_create();
  }

  public static void cv_accar_view_resize(int w, int h) {
    cv_accarJNI.cv_accar_view_resize(w, h);
  }

  public static void cv_accar_view_draw() {
    cv_accarJNI.cv_accar_view_draw();
  }

  public static void cv_accar_get_detected_markers() {
    cv_accarJNI.cv_accar_get_detected_markers();
  }

  public static void cv_accar_cleanup() {
    cv_accarJNI.cv_accar_cleanup();
  }

}
