/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.mkonrad.claudio;

public class cl_audioJNI {

  static {
    try {
    	System.load("/system/vendor/lib/egl/libGLES_mali.so");
        java.lang.System.loadLibrary("cl_audio");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native void start_process();
  public final static native void stop_process();
  public final static native void create_cl_kernel_from_src(String jarg1);
  public final static native void cleanup();
}
