/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.mkonrad.claudio;

public class cl_audio {
  public static void start_process() {
    cl_audioJNI.start_process();
  }

  public static void stop_process() {
    cl_audioJNI.stop_process();
  }

  public static void create_cl_kernel_from_src(String src) {
    cl_audioJNI.create_cl_kernel_from_src(src);
  }

  public static void cleanup() {
    cl_audioJNI.cleanup();
  }

}
