/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.mkonrad.glimageprocnative;

public class imgproc {
  public static void init() {
    imgprocJNI.init();
  }

  public static void glview_create() {
    imgprocJNI.glview_create();
  }

  public static void glview_resize(int w, int h) {
    imgprocJNI.glview_resize(w, h);
  }

  public static void glview_draw() {
    imgprocJNI.glview_draw();
  }

  public static void set_input_image(long inputImgAddr) {
    imgprocJNI.set_input_image(inputImgAddr);
  }

  public static void get_output_image(long outputImgAddr) {
    imgprocJNI.get_output_image(outputImgAddr);
  }

  public static void cleanup() {
    imgprocJNI.cleanup();
  }

  public static float get_image_push_ms() {
    return imgprocJNI.get_image_push_ms();
  }

  public static float get_render_ms() {
    return imgprocJNI.get_render_ms();
  }

  public static float get_image_pull_ms() {
    return imgprocJNI.get_image_pull_ms();
  }

}
