/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.mkonrad.glimageprocnative;

public class imgprocJNI {

  static {
    try {
        java.lang.System.loadLibrary("imgproc");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native void init();
  public final static native void glview_create();
  public final static native void glview_resize(int jarg1, int jarg2);
  public final static native void glview_draw();
  public final static native void set_input_image(long jarg1);
  public final static native void get_output_image(long jarg1);
  public final static native void cleanup();
  public final static native float get_image_push_ms();
  public final static native float get_render_ms();
  public final static native float get_image_pull_ms();
}
